---
- ec2:
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ item['type'] | default('t2.micro')}}"
    group_id: "{{ my_group_id }}"
    instance_tags:
      Name: "{{ item['name'] }}"
      instance_role: "{{ item['role'] }}"
      env: "{{ my_env }}"
    exact_count: "{{ item['count'] | default(1)}}"
    count_tag:
      Name: "{{ item['name'] }}"
      instance_role: "{{ item['role'] }}"
      env: "{{ my_env }}"
    wait: yes
    volumes:
      - volume_size: "{{ item['rootvol']['size'] | default(10)}}"
        device_type: "{{ item['rootvol']['type'] | default('gp2')}}"
        device_name: /dev/sda1
        delete_on_termination: true
    assign_public_ip: yes
    vpc_subnet_id: "{{ my_vpc_subnet_id }}"
  with_items:
    - "{{ my_items }}"
  register: ec2

- set_fact:
    ec2_instances:  "{{ ec2.results[0].instances }}"
  when: ec2.results[0].instances is defined and ec2.results[0].instances

- set_fact:
    ec2_instances: "{{ ec2.results[0].tagged_instances }}"
  when: ec2.results[0].tagged_instances is defined and ec2.results[0].tagged_instances
